### ISSUE TITLE
fileXioGetStat not working for host

### ISSUE THREAD

**Issue by fjtrujy** [ps2dev/ps2sdk#101]
Hello,
The `fileXioGetStat` function always return `-19` when I tried to access through `host` drive.

To give you more info, I'm using `ps2-client` to debug/run the `.elf`, so for instance if it tries to get stat for something like `host:test` giving that `test` is a folder, it always return `-19`

Thanks

**Comment by sp193** [comment]
Code 19 is ENODEV. If you're not using a development TOOL unit, the CEX PlayStation 2 console does not support the host device.

I'm not sure what you have done. ps2link itself will provide access to host, but you must have done something to prevent host from being accessed. For example, if you reboot the IOP and load UDPTTY, then you will still get debug messages via ps2client, but access to host will not work.

ps2link also has [no support for getstat()](https://github.com/ps2dev/ps2link/blob/master/iop/net_fsys.c#L306).

**Comment by fjtrujy** [comment]
Hello @sp193 ,

Maybe I didn't explain properly. 
As you probably know I'm doing the Retroarch version for PS2, in order to create the folders and file configuration I'm using functions as `fileXioGetStat` and later `FIO_S_ISDIR` to check for instance is it is a dir.

I can say that I can access to the `host` without any problem, even "debugging", I can list files, read and even write.

But the problem is that when I'm launching `RetroArch` from the `ps2-client`, it tries to create the folders and configuration in the `host`, because from there is where right now I'm executing the `.elf`, and it always fails with the code -19 in the call to `fileXioGetStat(path, &buf);`

I don't know if this useful, but when I'm debugging from `PS2Client`, in order to don't lose the connection with console I have this piece of code:

```
   SifInitRpc(0);
#if !defined(DEBUG)
   /* Comment this line if you don't wanna debug the output */
   while(!SifIopReset(NULL, 0)){};
#endif
   while(!SifIopSync()){};
   SifInitRpc(0);
```

If you see when I'm debugging, I skip the `while(!SifIopReset(NULL, 0)){};`

Sorry If the same that I'm saying does not make sense.
Thanks

**Comment by sp193** [comment]
You have to debug this on your end. ENODEV means that the device does not exist, and is an error code that is returned by IOMAN (or iomanX). If you are sure that the necessary modules are loaded (since you can read/write to files on host:), then the device name might have been specified incorrectly to the call to getstat().

**Comment by sp193** [comment]
On a side note, you may also encounter this error if you access mass: before the device driver has initialized the device. USBHDFSD will return [ENODEV under such a condition](https://github.com/ps2dev/ps2sdk/blob/master/iop/usb/usbhdfsd/src/fs_driver.c#L229).
But for the host device provided by ps2link, it can be assumed that the device is already present at boot.

I know that you have been working on PicoDrive and RetroArch. Awesome work, by the way. It's not everday when people are willing to take up difficult projects.

**Comment by fjtrujy** [comment]
However, if instead of doing
```
fileXioGetStat(path, &buf);
is_dir = FIO_S_ISDIR(buf.mode);
```
I do
```
is_dir = fioDopen(path);
```

It returns proper values.

**Comment by sp193** [comment]
Try using ``fileXioDOpen()`` instead. If it fails, I would examine how you have loaded iomanX and fileXio. The problem with not rebooting the IOP, is that you will have whatever that was previously loaded, and that could also lead to conflicts...

**Comment by sp193** [comment]
I am starting to have some flashbacks to my earlier PS2 development days. Somehow, some devices will not correctly appear in iomanX's device list, but I only experienced it in 2009.

What iomanX does, is a hack. Rightfully, we would have reboot the IOP and made iomanX and fileXio replacements for IOMAN and FILEIO, but that is not what we do here. So iomanX will steal the existing device list from IOMAN, while devices registered later on will be added directly to iomanX since iomanX hooks onto addDrv as well.

It was never clear to me why it ever happened and I never recalled experiencing it again, so it could be that the hack does not work very well. So to avoid that risk, you could load iomanX and fileXio as early as possible.

Of course, you may not be able to do that here because you want to use ps2link's host device.

**Comment by fjtrujy** [comment]
> Try using `fileXioDOpen()` instead. If it fails, I would examine how you have loaded iomanX and fileXio. The problem with not rebooting the IOP, is that you will have whatever that was previously loaded, and that could also lead to conflicts...

It is workings as well with `fileXioDOpen()`

**Comment by sp193** [comment]
Then iomanX is aware of the host device, but yet it is returning a different value from what I can tell from the ps2link source code. Are you using a custom version of ps2link?

**Comment by fjtrujy** [comment]
So, about `ps2link`, I'm just using the one that is installed by the `ps2toolchain`

On the other hand `fileXioGetStat()` it is working perfectly with `MC0`, `MC1`, `MASS`, these are the unit that I have probe.

For now the code that I have as workaround is something like this:
```
fileXioGetStat(path, &buf);
If (buf.mode) {
   is_dir = FIO_S_ISDIR(buf.mode);
} else {
   int open_dir;
   open_dir = fioDopen(path);
   is_dir = open_dir > 0;
   fioDclose(open_dir);
}
```

I have written this code down from my phone, it could ha errors there.

Thanks

**Comment by sp193** [comment]
But ps2link is not built as part of ps2toolchain. You're probably thinking of ps2client.
You should also check the return value of getstat(), not just whether there are bits set.

**Comment by fjtrujy** [comment]
> But ps2link is not built as part of ps2toolchain. You're probably thinking of ps2client.
> You should also check the return value of getstat(), not just whether there are bits set.

Yes, you were right, I was speaking about `ps2client`, I'm not using `ps2link` at all.
Yes, I'm checking as well the return value of `getstat`, as I said it just was written down myself from the phone device. The value that it returns it is `-19`

Should I just create a dummy project and send over here?

Probably is the easiest way to check it.
Thanks

**Comment by sp193** [comment]
Thanks, but you need to know what exactly you want fixed. Do you need help for your project, to fix ps2link or to identify a bug in the PS2SDK (and where?). fileXioGetStat() is working, since you wrote that it works fine when used with other devices.

ps2link's host device just does not support getstat(), although I am not sure why you get -19 instead of -5. That's why I asked which version of ps2link you used, as this difference might be caused by you using a different/custom version, which returns a different value from the one in the Github repository.
But either way, it will not just work, unless somebody implements more code in ps2link (and likely ps2client).

Most people just use this for debugging during development. Once you reboot the IOP, the host device cannot be accessed.

**Comment by fjtrujy** [comment]
Hello,
I will try to install the latest version of ps2link in the memory card and check if this is the error, I don't remember exactly the version that I used for ps2link, it was long time ago.


> Most people just use this for debugging during development. Once you reboot the IOP, the host device cannot be accessed.

Yeah, that why in order to keep debuging, I skip this line `while(!SifIopReset(NULL, 0)){};` I'm not sure  if this is the root of my problem.

Let me attach more information here, maybe it is not an issue and it is just that I'm trying to do something that is not possible.

Thanks
