### ISSUE TITLE
Possible bug in ps2_sbrk due to size_t parameter

### ISSUE THREAD

**Issue by glampert** [ps2dev/ps2sdk#13]
I'm encountering a few cases where `malloc` is returning NULL with roughly ~14MB of system memory allocated. At first I was suspecting the issue was with heap fragmentation from previous `free()`s but looking at the implementation in the libc dir, I noticed that free might call `ps2_sbrk` with a negative value. Excerpt from `alloc.c`:

    /* We need to free (heap top) - (prev->ptr + prev->size), or else
    we'll end up with an unallocatable block of heap.  */
    heap_top = ps2_sbrk(0);
    size = (u32)heap_top - (u32)(cur->prev->ptr + cur->prev->size);
    ps2_sbrk(-size);

There's another negated parameter case above that section too.

However when looking at the implementation of `ps2_sbrk` I was surprised to find the `increment` parameter declared as `size_t`, which is unsigned.

`sbrk.c`:

    void *ps2_sbrk(size_t increment)
    {
        static void * _heap_ptr = &_end;
        void *mp, *ret = (void *)-1;

        if (increment == 0)
            return _heap_ptr;

        /* If the area we want to allocated is past the end of our heap, we have a problem. */
        mp = _heap_ptr + increment;
        if (mp <= EndOfHeap()) {
            ret = _heap_ptr;
            _heap_ptr = mp;
        }

        return ret;
    }

So when `free` tries to roll back the heap, it will actually just add more to the already allocated region, due to signed => unsigned promotion! To match the signature of [Unix `sbrk`](https://en.wikipedia.org/wiki/Sbrk#Function_signatures_and_behavior), `ps2_sbrk` should be taking a signed type.

Please advise if you agree that this is a bug in the code and I'll promptly create a pull request with the fix.

Thanks.

**Comment by sp193** [comment]
Did you test whether the glitch happens because of the mixing of signed and unsigned types at that point?
Maybe I'm wrong because I am not a master of maintaining C compilers, but doesn't casting a signed negative number to unsigned simply means that the compiler can forget sign extension? Which wouldn't matter here because the numbers are all 32-bit?
Did you enable the debug code to check if your buffers are getting overrun? The linked list nodes that malloc and free use, are stored before the buffers that are returned. So if those pointers are trashed up, free may be unable to free the memory that you allocated.

**Comment by glampert** [comment]
Hi sp193, I was also unsure about how that `-` operator would behave, but it seems you are correct. Looking into [this](http://stackoverflow.com/q/8026694/1198654) and [this](http://stackoverflow.com/q/9474699/1198654) SO threads, and [this example](http://ideone.com/qUQXwX) I came up with, corroborate that.

It seems that the problem is not in `ps2_sbrk` then. I'll further investigate my own code for buffer overruns. I'm also considering switching to dlmalloc, which has more debugging facilities. Thanks for the quick reply anyway ;).

**Comment by sp193** [comment]
But anyway, are you certain that sbrk is supposed to accept a signed input? There's not much information on this low-level function.
If you are, then maybe we can work out something just for correctness.

**Comment by glampert** [comment]
@sp193 The only info I have about the function signature are from [this POSIX page](http://pubs.opengroup.org/onlinepubs/7908799/xsh/brk.html) and [this wikipedia page](https://en.wikipedia.org/wiki/Sbrk), which both show it as taking a `intptr_t increment`. `intptr_t` is the signed equivalent of `uintptr_t`, which by the C standard is "an integer type capable of holding a value converted from a void pointer and then be converted back to that type with a value that compares equal to the original pointer".

If you're willing to go the extra mile, I think it would be nice to include a copy of [`stdint.h`](http://www.cplusplus.com/reference/cstdint/) to the C lib project and then make the sbrk fix to `intptr_t`.

**Comment by sp193** [comment]
Thanks. I think that if anything should be done, it'll be the change from u32 to s32.
I don't think that it's a good idea to introduce a stdint.h file because it seems to have been introduced with C99, which our compiler isn't fully compliant with and code built for the older C standards wouldn't need it anyway.

**Comment by glampert** [comment]
@sp193 Great! Yes indeed stdint.h is C99. It would also be redundant with tamtypes.h, so not really a must have.
