### ISSUE TITLE
MCMAN dynamic linking with SIO2MAN causing issues with MX4SIO

### ISSUE THREAD

**Issue by rickgaiser** [ps2dev/ps2sdk#317]
MCMAN uses dynamic linking with SIO2MAN here:
https://github.com/ps2dev/ps2sdk/blob/3df67b619704328e1093ca01a729f09f542408f6/iop/memorycard/mcman/src/main.c#L171-L240

For MX4SIO to work it needs to "hook" into these functions, as it does here:
https://github.com/ps2dev/ps2sdk/blob/3df67b619704328e1093ca01a729f09f542408f6/iop/sio/mx4sio_bd/src/sio2man_hook.c#L131-L151

When MX4SIO and MCMAN try to use SIO2MAN at the same time this will cause issues. As is the case with OPL here:
https://github.com/ps2homebrew/Open-PS2-Loader/issues/663

Is there a reason for MCMAN in ps2sdk to have this dynamic linking?
Can we simplify MCMAN to use a standard import table? Then import SIO2MAN / XSIO2MAN / RSIO2MAN
Also what does the "xfromman.irx" compile option in MCMAN do?

**Comment by sp193** [comment]
The Sony way of making an SDK, appeared to have compatible IOP modules part of the same SDK.
Our SDK is a Frankenstein monster, whereby we generally coded modules based on modules from various SDK versions. Maybe that's why they tried to do something non-standard, to make this module as.... compatible as possible. But static linking of imports is the natural way to do things and is handled by the IOP kernel (no need to write code that might contain additional bugs).

It's probably for a case where the software somehow used rom0:SIO2MAN, but a newer MCMAN module is required.

FROMMAN probably stood for Flash ROM MANager. It's a driver for the 8MB embedded flash storage in the PSX. I guess, @uyjulian made this project possibly compile into that module.
