### ISSUE TITLE
HDD problems PS2SDK Update a while back,

### ISSUE THREAD

**Issue by Rikimaruaxu** [ps2dev/ps2sdk#329]
I have a Crucial BX500 SSD, And it worked in an earlier build of OPL But not one a few days later. I already went through and reverted all changes made between the two versions of OPL and none allowed my drive to work, So my best option is here. The time span of changes is between these two commits 01f3db7 and 133d923 Of PS2SDK, Something changed between these two versions that stopped my SSD from being detected at all, Tested through both a gamestar hdd adapter and an official with a bitfunx 2.0 sata board. A Seagate Barracuda 160 GB Sata drive from 2011 still works but does not have the same capacity of my 500Gb drive, so It seems to be some sort of issue that directly messes with certain SSD's

If there is anything anyone here can think of for me to test or log I can. I am severely limited in my understanding of the file structure of these gits so I don't think I'm correct but #199  could be a place to look or if someone here knows where the hdd detection code is maybe they could find the actual PR that broke it. From what I can tell there are other SSD users that don't have a problem so It might be specific to crucial drives.

**Comment by AcidReach** [comment]
I have the same issue. Same HDD crucial BX500 1TB SSD.
The HDD is detected without issue on the ps2 in HDDManager in the MISC folder. It formats fine using this tool. 
I load OPL and it takes 5 minutes or so to load with a 221 HDD error. No OPL partition is created. Tried manually creating the partition but same result. 
Loaded games using hdl_dump in Debian and the partitions show on the PS2 in HDD Manager but OPL won't load them. Same 221 error.
Tried bitfunx 2.0 sata adapter in the original Sony Network Adapter, tried Gamestar PS2 SATA HDD adapter.
Both give the same result.

Previously been using a 500GB IDE HDD and 1TB sata 2.5 drive which both worked perfectly in all scenarios.

Hope this info helps someone fix this.

**Comment by AcidReach** [comment]
Just to confirm, OPL v1.0.0 works properly and games are listed and can load.
OPL v.1.1.0 does not work so the change that made it stop working was between the 2 versions of PS2SDK that was used to compile these OPL versions.

**Comment by AcidReach** [comment]
Additional info.
I purchased a crucial MX500 as recommended and it did work! Except it has faulty sector so I sent back.
Got a new MX500.
The new one doesn't work with the latest beta but does work with OPL latest stable version which the BX500 did not.
Strange.

**Comment by sp193** [comment]
My 2-cents: it is very difficult to tell what is wrong if you're using adaptors. Electrically, SATA and ATA devices are different.
It is possible that the issue is with the adaptor itself, thus somehow becoming incompatible with whatever change that was mde.

From my experience long ago, those compatible network adaptors (i.e. not based on Sony hardware) at least used to have worse compatibility because they might have been built with incomplete knowledge of the IOP SSBUS and the Sony ATA's registers.

One major weakness was with enabling DMA, whereby they designed their hardware around our early ATAD module design... and did not realize that 0x80 can enable DMA. So when we changed the written value from 0x86 to 0x80 like Sony did, some of these adaptors stopped working. Just things like that.

So if anyone wants to go study this problem, I would try to identify the exact commit that brought about the problem and try to determine what exactly was the offending change. But there's just a possibility that it stopped working well because it wasn't a good design.

**Comment by Rikimaruaxu** [comment]
Which is fair, I do know the general commits where the issue starts. But I don't know where to begin identifying the problem. And since I havent had time to mess with my ps2 the past few months I dont even know if it magically fixed itself, But all in all it really seems like it is an issue specifically with something in these drives, since a kingston drive works. as does a samsung one. I'm sorry that I don't really have any additional info since for the most part anyone who could do something about it would need access to the same adapter and SSD,

**Comment by uyjulian** [comment]
https://github.com/ps2dev/ps2sdk/commit/6a7ce5a7235c9ae97ddb6f45d9a8a11cd10331cb appears to have done something

This doesn't seem to be an issue anymore. Reopen if this is not the case
