### ISSUE TITLE
Error compiling PS2SDK

### ISSUE THREAD

**Issue by InfinityCorp214** [ps2dev/ps2sdk#674]
Every time I try to compile the PS2SDK, I get the following error:

make[3]: Nothing to be done for 'install-exec-am'.
/bin/mkdir -p '/usr/local/ps2dev/ps2sdk/ports/share/doc/confuse'
/bin/mkdir -p '/usr/local/ps2dev/ps2sdk/ports/lib/pkgconfig'
/usr/bin/install -c -m 644 README.md AUTHORS LICENSE ChangeLog.md '/usr/local/ps2dev/ps2sdk/ports/share/doc/confuse'
/usr/bin/install -c -m 644 libconfuse.pc '/usr/local/ps2dev/ps2sdk/ports/lib/pkgconfig'
make[3]: Leaving directory '/usr/local/ps2dev/ps2dev/build/ps2sdk-ports/build/libconfuse'
make[2]: Leaving directory '/usr/local/ps2dev/ps2dev/build/ps2sdk-ports/build/libconfuse'
make[1]: Leaving directory '/usr/local/ps2dev/ps2dev/build/ps2sdk-ports/build/libconfuse'
../scripts/003-ps2sdk-ports.sh: Failed.

**Comment by mystyq** [comment]
Make sure you run the `build-extras` script

**Comment by fjtrujy** [comment]
I think you are mixing "concepts".
You said trying to compile `ps2sdk` however, your error is coming from `ps2sdk-ports` (which is another repository), finally the error probably is coming when you are trying to execute scripts from `psdev` (another repo).

Anyway, most probably your issue is about a missing dependency, but without the whole log is impossible to figure it out.
Please be sure you have installed all the dependencies and try it again.
https://github.com/ps2dev/ps2dev/blob/master/.github/workflows/compilation.yml#L33

If it is not working for you, please reopen the issue in `ps2dev` instead.

Cheers
