### ISSUE TITLE
Including <dirent.h> does not declare expected functions and structs

### ISSUE THREAD

**Issue by madebr** [ps2dev/ps2sdk#76]
This code at https://github.com/aap/librw/blob/b1c3c1dca8c5c2244ba7ecfacd50310f27a31b8e/src/base.cpp#L619-L657 does not compile because `DIR`, `direct`, `opendir`, `readdir`, `closedir` and `dirent` are undeclared.

CI output:
https://travis-ci.org/madebr/librw/jobs/403399765#L495

**Comment by sp193** [comment]
Which libc are you using? I do not have experience with using Newlib, but if you are using the ps2sdk's native libc: we don't have those functions implemented. The native PS2 kernel libraries actually use Unix-like I/O functions. So you might need to write your own wrappers around dopen(), dread() etc. Keeping in mind that we have two I/O libraries (choose one!)

**Comment by madebr** [comment]
The project is using the ps2toolchain without modifications, so newlib 1.10.0.
I might have filed this issue to the wrong ps2dev project.

**Comment by sp193** [comment]
I think it is okay to have it open here too. Right now, we were also trying to solve the problem where we have two libcs...

Unfortunately, our version of Newlib is quite old, due to a problem with our compiler. But I read that Ragnarok2040 actually had fix for that and ported modern versions of it.

However, he has not gotten back to me on what he needed me to do. I mean, I think his work is done, but he did not really indicate that...

So if newer versions of Newlib do have the necessary functions implemented, updating our Newlib version might be the answer for the long run.

**Comment by fjtrujy** [comment]
Hello,
I think that after the #108 now this issue can be closed.
What do you think @rickgaiser ?
@madebr can you check if using the latest status of `ps2toolchain` (which will use the latest status of `ps2sdk` ) if it is now compiling?

It ideally should compile out of the box.

Thanks.

**Comment by rickgaiser** [comment]
Yes, this issue should now be solved. I don't expect @madebr to still be working on this after 2 years. So I'm closing the issue.
